# Generated by Django 5.2.1 on 2025-05-27 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asignados',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Personal Asignado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PLAN', 'Planificación'), ('EJE', 'En Ejecución'), ('SUS', 'Suspendido'), ('COM', 'Completado'), ('CAN', 'Cancelado')], default='PLAN', max_length=4, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
