# Generated by Django 5.2.1 on 2025-05-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_options_proyecto_asignados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Foto del Proyecto'),
        ),
    ]
