# Generated by Django 5.2.1 on 2025-06-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_pago_options_pago_fecha_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomina',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_process_nomina', 'Puede procesar nóminas'), ('can_cancel_nomina', 'Puede cancelar nóminas')], 'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
        migrations.AddField(
            model_name='nomina',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='ultimo_cambio_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='periodo',
            field=models.CharField(max_length=7),
        ),
    ]
