# Generated by Django 5.2.1 on 2025-05-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('contacto', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código del material'),
        ),
        migrations.AddField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='material',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ubicación en almacén'),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('l', 'Litro')], default='unidad', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en stock'),
        ),
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiales.categoriamaterial', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiales.proveedor', verbose_name='Proveedor'),
        ),
    ]
