# Generated by Django 5.2.1 on 2025-05-31 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def update_unidad_medida(apps, schema_editor):
    Material = apps.get_model('materiales', 'Material')
    # Actualizar los valores que exceden 3 caracteres
    Material.objects.filter(unidad_medida__gt='un').update(unidad_medida='un')

class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_categoriamaterial_proveedor_material_codigo_and_more'),
    ]

    operations = [
        migrations.RunPython(update_unidad_medida),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['codigo'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='materiales.categoriamaterial'),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='materiales.proveedor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(
                max_length=5,
                choices=[
                    ('kg', 'Kilogramos'),
                    ('g', 'Gramos'),
                    ('l', 'Litros'),
                    ('ml', 'Mililitros'),
                    ('m', 'Metros'),
                    ('cm', 'Centímetros'),
                    ('m2', 'Metros cuadrados'),
                    ('m3', 'Metros cúbicos'),
                    ('un', 'Unidad'),
                    ('pkg', 'Paquete'),
                ],
                default='un'
            ),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
