# Generated by Django 5.2.1 on 2025-05-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('m', 'Metros'), ('cm', 'Centímetros'), ('m2', 'Metros cuadrados'), ('m3', 'Metros cúbicos'), ('un', 'Unidad'), ('pkg', 'Paquete')], default='un', max_length=5),
        ),
    ]
