# Generated by Django 5.2.1 on 2025-06-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
