# Generated by Django 5.2.1 on 2025-06-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('gestionar_usuarios', 'Puede gestionar usuarios'), ('gestionar_proyectos', 'Puede gestionar proyectos'), ('gestionar_materiales', 'Puede gestionar materiales'), ('gestionar_nomina', 'Puede gestionar nómina'), ('ver_reportes', 'Puede ver reportes'), ('gestionar_asistencias', 'Puede gestionar asistencias')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
