# Generated by Django 5.1.7 on 2025-05-22 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('estado', models.CharField(choices=[('PLAN', 'Planificación'), ('PROG', 'En progreso'), ('SUSP', 'Suspendido'), ('COMP', 'Completado')], default='PLAN', max_length=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('arquitecto', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ARQ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_disenadas', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('trabajadores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'TEC'}, related_name='obras_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
