# Generated by Django 5.2.1 on 2025-05-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_obras_options_obras_avance_obras_descripcion_and_more'),
        ('proyectos', '0002_alter_proyecto_options_proyecto_asignados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='nombre',
        ),
        migrations.AddField(
            model_name='obras',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='proyectos.proyecto', verbose_name='Proyecto asociado'),
            preserve_default=False,
        ),
    ]
